"use client";
import MenuContextProvider from "@/context/MenuContext";
import "../styles/globals.scss";
import { QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import MainLayout from "@/components/layout/MainLayout";
import { QueryClient } from "@tanstack/react-query";
import { ConfigProvider } from "antd";
const metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
    },
  },
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ConfigProvider
          theme={{
            token: {
              // Seed Token
              colorPrimary: "#023020",
              borderRadius: 5,
              colorBgContainer: "#ffffff", //a6b5ad
            },
          }}
        >
          <QueryClientProvider client={queryClient}>
            <ReactQueryDevtools initialIsOpen={false} />
            <MenuContextProvider>{children}</MenuContextProvider>
          </QueryClientProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
