"use client";
import MenuContextProvider from "@/context/MenuContext";
import "../styles/globals.scss";
import { ConfigProvider } from "antd";
import { QueryClient, QueryClientProvider } from "react-query";
import { ReactQueryDevtools } from "react-query/devtools";

const metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
    },
  },
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#023020",
              borderRadius: 5,
              colorBgContainer: "#ffffff", //a6b5ad
            },
          }}
        >
          <QueryClientProvider client={queryClient}>
            <ReactQueryDevtools initialIsOpen={false} />
            <MenuContextProvider>{children}</MenuContextProvider>
          </QueryClientProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}